(()=>{'use strict';
const $=id=>document.getElementById(id),PI=Math.PI,MPL=2.435e18;
const D={logZ:-16,MKK:1e3,M6:2e10,Mb:2e10,cV:Math.sqrt(4*PI),T:131.515,gstar:106.75,eps:4.45e-9,omegaMax:.01,scaleChoice:'mkk',Lambda0:1e3,cX:1,safety:1,lambdaQ:0,mq:0,loopChoice:'mkk',Loop0:1e3,NJ:12};
const num=id=>Number($(id).value),fmt=x=>!Number.isFinite(x)?'–':((Math.abs(x)>0&&Math.abs(x)<1e-3)||Math.abs(x)>=1e6?x.toExponential(4).replace('.',','):x.toLocaleString('de-DE',{maximumFractionDigits:6}));
function scale(choice,p,custom){return choice==='mkk'?p.MKK:choice==='m6'?p.M6:choice==='mb'?p.Mb:custom}
function read(){return{logZ:num('logZ'),MKK:num('MKK'),M6:num('M6'),Mb:num('Mb'),cV:num('cV'),T:num('T'),g:num('gstar'),eps:num('eps'),om:num('omegaMax'),sc:$('scaleChoice').value,L0:num('Lambda0'),cX:Math.abs(num('cX')),s:Math.max(0,num('safety')),lq:Math.abs(num('lambdaQ')),mq:Math.abs(num('mq')),lc:$('loopChoice').value,LJ:num('Loop0'),NJ:Math.max(0,num('NJ'))}}
function calc(p,zOverride){const Z=zOverride??Math.pow(10,p.logZ);if(!(Z>0&&p.MKK>0&&p.M6>0&&p.Mb>0&&p.cV>0&&p.T>0&&p.g>0&&p.om>0&&p.s>0&&Math.abs(p.eps)>0))return null;const sqrtV=p.cV/p.MKK,F0=p.Mb*p.Mb*sqrtV,sq=Math.sqrt(Z),fe=F0*sq,H=Math.sqrt(PI*PI*p.g/90)*p.T*p.T/MPL,rho=PI*PI*p.g*Math.pow(p.T,4)/30,pd=p.eps*fe*p.T,omega=.5*pd*pd/rho,Ebg=Math.sqrt(Math.abs(pd)),E=Math.max(p.T,Ebg,H),Lam=scale(p.sc,p,p.L0),loopLam=scale(p.lc,p,p.LJ),Lsc=p.cX>0?sq*Lam/Math.pow(p.cX,.25):Infinity,gateRatio=p.s*E/Lsc,fmax=Math.sqrt(2*p.om*rho)/(Math.abs(p.eps)*p.T),zBack=Math.pow(fmax/F0,2),zStrong=p.cX>0?Math.pow(p.s*E/Lam,2)*Math.sqrt(p.cX):0,cmax=Z*Z*Math.pow(Lam/(p.s*E),4),lambdaCan=p.lq/(Z*Z),lambdaLoop=lambdaCan/(16*PI*PI),lambdaMax=16*PI*PI*Z*Z,mphi=p.mq/sq,mqRatio=p.mq===0?0:mphi/H,mqMax=sq*H,loopRatio=p.NJ/(16*PI*PI)*Math.pow(loopLam/fe,2),gJ=p.T/fe,kkRatio=E/p.MKK,cKKmax=Z*Z*Math.pow(p.MKK/(p.s*E),4),Lmin=p.s*E*Math.pow(Math.max(p.cX,0),.25)/sq,window=zStrong<=zBack;return{Z,sqrtV,F0,fe,H,rho,pd,omega,Ebg,E,Lam,loopLam,Lsc,gateRatio,fmax,zBack,zStrong,cmax,lambdaCan,lambdaLoop,lambdaMax,mphi,mqRatio,mqMax,loopRatio,gJ,kkRatio,cKKmax,Lmin,window}}
function applyPreset(v){const P={kk:{logZ:-16,sc:'mkk',L0:1e3,cX:1,s:1,lq:0,mq:0,lc:'mkk',LJ:1e3,NJ:12},uv:{logZ:-16,sc:'m6',L0:2e10,cX:1,s:1,lq:0,mq:0,lc:'m6',LJ:2e10,NJ:12},protected:{logZ:-16,sc:'m6',L0:2e10,cX:1,s:1,lq:0,mq:0,lc:'mkk',LJ:1e3,NJ:12},potential:{logZ:-16,sc:'m6',L0:2e10,cX:1,s:1,lq:1,mq:1e-10,lc:'m6',LJ:2e10,NJ:12}}[v];if(!P)return;$('logZ').value=P.logZ;$('scaleChoice').value=P.sc;$('Lambda0').value=P.L0;$('cX').value=P.cX;$('safety').value=P.s;$('lambdaQ').value=P.lq;$('mq').value=P.mq;$('loopChoice').value=P.lc;$('Loop0').value=P.LJ;$('NJ').value=P.NJ}
function scenarioRow(label,Lam,r,p){const Lsc=Math.sqrt(r.Z)*Lam/Math.pow(Math.max(p.cX,1e-300),.25),zmin=Math.pow(p.s*r.E/Lam,2)*Math.sqrt(p.cX),ok=zmin<=r.zBack;return'<tr><td>'+label+'</td><td>'+fmt(Lam)+'</td><td>'+fmt(Lsc)+'</td><td>'+fmt(zmin)+'</td><td>'+(ok?'JA · Faktor '+fmt(r.zBack/Math.max(zmin,1e-300)):'NEIN')+'</td></tr>'}
function render(){const p=read(),r=calc(p);if(!r){$('message').textContent='Ungültige Eingaben.';return}$('feff').textContent=fmt(r.fe);$('omega').textContent=fmt(r.omega);$('Eaudit').textContent=fmt(r.E);$('Lsc').textContent=fmt(r.Lsc);$('ratio').textContent=fmt(r.gateRatio);$('zBack').textContent=fmt(r.zBack);$('zStrong').textContent=fmt(r.zStrong);$('cmax').textContent=fmt(r.cmax);$('lambdaCan').textContent=fmt(r.lambdaLoop);$('mqRatio').textContent=fmt(r.mqRatio);$('loopRatio').textContent=fmt(r.loopRatio);$('cKKmax').textContent=fmt(r.cKKmax);
$('backAudit').textContent=r.omega<=p.om?'PASS':'FAIL';$('kkAudit').textContent=r.kkRatio<1?'PASS':'E≥MKK';$('scAudit').textContent=p.cX===0?'OPERATOR=0 INPUT':r.gateRatio<=1?(r.gateRatio<=.3?'PASS':'MARGINAL'):'FAIL';const potOK=(p.lq===0||r.lambdaLoop<1)&&(p.mq===0||r.mqRatio<1),loopOK=r.loopRatio<1;$('radAudit').textContent=potOK&&loopOK?((p.lq===0&&p.mq===0)?'PROTECTED INPUT':'PASS'):'FAIL';
const w=$('window');if(r.window){w.className='window '+(r.zBack/r.zStrong>10?'pass':'warnbox');w.querySelector('span').textContent='Konditionales Normfenster: '+fmt(r.zStrong)+' ≤ Zeff ≤ '+fmt(r.zBack)+'. Breite: Faktor '+fmt(r.zBack/Math.max(r.zStrong,1e-300))+'.'}else{w.className='window fail';w.querySelector('span').textContent='Kein gemeinsames Normfenster: Zmin,strong='+fmt(r.zStrong)+' liegt über Zmax,back='+fmt(r.zBack)+'.'}
$('scenarioRows').innerHTML=scenarioRow('O(1) am MKK',p.MKK,r,p)+scenarioRow('O(1) am M₆',p.M6,r,p)+scenarioRow('O(1) an Mᵦ',p.Mb,r,p)+scenarioRow('gewählte Skala',r.Lam,r,p);
$('more').innerHTML='√Vᵂ = '+fmt(r.sqrtV)+' GeV⁻¹<br>F₀=Mᵦ²√Vᵂ = '+fmt(r.F0)+' GeV<br>H(T) = '+fmt(r.H)+' GeV<br>φ̇req = '+fmt(r.pd)+' GeV²<br>√|φ̇| = '+fmt(r.Ebg)+' GeV<br>ρrad = '+fmt(r.rho)+' GeV⁴<br>T/feff = '+fmt(r.gJ)+'<br>Eaudit/MKK = '+fmt(r.kkRatio)+'<br>λq,max(pert.) = '+fmt(r.lambdaMax)+'<br>mq,max(mφ≤H) = '+fmt(r.mqMax)+' GeV<br>Λ₀,min bei aktuellem Z = '+fmt(r.Lmin)+' GeV<br>erforderliche Unterdrückung eines MKK-Operators: |cX,KK|≤'+fmt(r.cKKmax);
let msg='';if(r.omega>p.om)msg+='Die gewählte Norm verfehlt das Rückwirkungsgate. ';else msg+='Die kinetische Rückwirkung liegt unter der gewählten Grenze. ';if(r.gateRatio>1)msg+='Der führende X²-Operator wird vor der relevanten elektroschwachen Skala stark gekoppelt. ';else if(r.gateRatio>.3)msg+='Der X²-Cutoff liegt nur knapp über der Auditskala; höhere Operatoren und Unsicherheiten sind relevant. ';else msg+='Der X²-Benchmark besitzt einen deutlichen Cutoffabstand. ';if(r.cKKmax<1e-12)msg+='Jeder am KK-Maßstab erzeugte X²-Operator müsste auf |cX,KK|≲'+fmt(r.cKKmax)+' unterdrückt werden. ';if(p.lq>0&&r.lambdaLoop>=1)msg+='Die kanonische Quartik ist nicht perturbativ. ';if(p.mq>0&&r.mqRatio>=1)msg+='Die kanonische Mode ist schwerer als H und erfüllt den leichten Driftbenchmark nicht. ';if(r.loopRatio>=1)msg+='Die NDA-Stromschleife destabilisiert die kleine Norm. ';else msg+='Die isolierte NDA-Stromschleife bleibt unter der Baum-Norm. ';$('message').textContent=msg+'Null gesetzte Potentialoperatoren sind nur mit einer tatsächlichen Verschiebungssymmetrie zulässig.';draw(r,p)}
function draw(r,p){const c=$('chart'),b=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(320,b.width),h=Math.max(300,b.height);c.width=w*d;c.height=h*d;const g=c.getContext('2d');g.setTransform(d,0,0,d,0,0);g.clearRect(0,0,w,h);const pad={l:58,r:24,t:22,b:44},W=w-pad.l-pad.r,H=h-pad.t-pad.b,xlo=-20,xhi=0,ylo=-8,yhi=20,X=x=>pad.l+W*(x-xlo)/(xhi-xlo),Y=y=>pad.t+H*(yhi-y)/(yhi-ylo);g.strokeStyle='#302b45';g.fillStyle='#afa8c3';g.font='10px system-ui';for(let i=0;i<=10;i++){const x=xlo+(xhi-xlo)*i/10,xx=X(x);g.beginPath();g.moveTo(xx,pad.t);g.lineTo(xx,pad.t+H);g.stroke();if(i%2===0)g.fillText(x.toFixed(0),xx-7,h-10)}for(let j=0;j<=7;j++){const y=ylo+(yhi-ylo)*j/7,yy=Y(y);g.beginPath();g.moveTo(pad.l,yy);g.lineTo(pad.l+W,yy);g.stroke();g.fillText(y.toFixed(0),5,yy+3)}function path(fn,col){g.strokeStyle=col;g.lineWidth=2.2;g.beginPath();for(let i=0;i<=260;i++){const x=xlo+(xhi-xlo)*i/260,z=Math.pow(10,x),rr=calc(p,z),y=fn(rr);i?g.lineTo(X(x),Y(y)):g.moveTo(X(x),Y(y))}g.stroke()}path(rr=>Math.log10(Math.min(1e30,Math.max(1e-30,rr.Lsc))),'#7fe0b5');path(rr=>Math.log10(Math.max(1e-30,rr.E)),'#79d3ff');g.strokeStyle='#c5afff';g.setLineDash([6,5]);g.beginPath();g.moveTo(pad.l,Y(Math.log10(p.MKK)));g.lineTo(pad.l+W,Y(Math.log10(p.MKK)));g.stroke();g.setLineDash([]);const vline=(z,col,label)=>{if(!(z>0))return;const x=Math.log10(z);if(x<xlo||x>xhi)return;g.strokeStyle=col;g.setLineDash([5,4]);g.beginPath();g.moveTo(X(x),pad.t);g.lineTo(X(x),pad.t+H);g.stroke();g.setLineDash([]);g.fillStyle=col;g.fillText(label,X(x)+3,pad.t+12)};vline(r.Z,'#ffad72','Z');vline(r.zBack,'#ff829f','Zback');vline(r.zStrong,'#ffe07d','Zstrong');g.fillStyle='#bcb5cf';g.fillText('log₁₀ Zeff',w/2-28,h-8);g.save();g.translate(13,h/2+28);g.rotate(-PI/2);g.fillText('log₁₀ Energie [GeV]',0,0);g.restore()}
$('preset').onchange=()=>{applyPreset($('preset').value);render()};$('run').onclick=render;$('setBack').onclick=()=>{const r=calc(read());if(r){$('logZ').value=Math.log10(r.zBack);render()}};$('setLambda').onclick=()=>{const r=calc(read());if(r){$('scaleChoice').value='custom';$('Lambda0').value=r.Lmin;render()}};$('profile').onclick=()=>location.href='./baryogenesis-strong-coupling.json';document.querySelectorAll('input,select').forEach(x=>x.addEventListener('change',()=>{if(x.id!=='preset')render()}));addEventListener('resize',render,{passive:true});render();
})();