(()=>{'use strict';
const $=id=>document.getElementById(id),PI=Math.PI,LIMIT=3.3427110946928156e-29;
const names=['Θ','Radion','Flux','Metrik-Skalar'];
const fmt=x=>!Number.isFinite(x)?'–':((Math.abs(x)>0&&Math.abs(x)<1e-3)||Math.abs(x)>=1e6?x.toExponential(4).replace('.',','):x.toLocaleString('de-DE',{maximumFractionDigits:6}));
const num=id=>Number($(id).value);
function zeros(n){return Array.from({length:n},()=>Array(n).fill(0))}
function transpose(A){return A[0].map((_,j)=>A.map(r=>r[j]))}
function mul(A,B){const C=Array.from({length:A.length},()=>Array(B[0].length).fill(0));for(let i=0;i<A.length;i++)for(let k=0;k<B.length;k++)for(let j=0;j<B[0].length;j++)C[i][j]+=A[i][k]*B[k][j];return C}
function jacobi(A){const n=A.length,V=zeros(n);for(let i=0;i<n;i++)V[i][i]=1;for(let it=0;it<500;it++){let p=0,q=1,m=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(Math.abs(A[i][j])>m){m=Math.abs(A[i][j]);p=i;q=j}if(m<1e-13)break;const ph=.5*Math.atan2(2*A[p][q],A[q][q]-A[p][p]),c=Math.cos(ph),s=Math.sin(ph);for(let k=0;k<n;k++)if(k!==p&&k!==q){const x=A[k][p],y=A[k][q];A[k][p]=A[p][k]=c*x-s*y;A[k][q]=A[q][k]=s*x+c*y}const app=c*c*A[p][p]-2*s*c*A[p][q]+s*s*A[q][q],aqq=s*s*A[p][p]+2*s*c*A[p][q]+c*c*A[q][q];A[p][p]=app;A[q][q]=aqq;A[p][q]=A[q][p]=0;for(let k=0;k<n;k++){const x=V[k][p],y=V[k][q];V[k][p]=c*x-s*y;V[k][q]=s*x+c*y}}return{values:A.map((r,i)=>r[i]),vectors:V}}
function cholesky(A){const n=A.length,L=zeros(n);for(let i=0;i<n;i++)for(let j=0;j<=i;j++){let s=A[i][j];for(let k=0;k<j;k++)s-=L[i][k]*L[j][k];if(i===j){if(s<=1e-15)return null;L[i][j]=Math.sqrt(s)}else L[i][j]=s/L[j][j]}return L}
function invLower(L){const n=L.length,X=zeros(n);for(let c=0;c<n;c++)for(let i=0;i<n;i++){let s=i===c?1:0;for(let k=0;k<i;k++)s-=L[i][k]*X[k][c];X[i][c]=s/L[i][i]}return X}
function inverse(A){const n=A.length,M=A.map((r,i)=>r.concat(Array.from({length:n},(_,j)=>i===j?1:0)));for(let c=0;c<n;c++){let p=c;for(let i=c+1;i<n;i++)if(Math.abs(M[i][c])>Math.abs(M[p][c]))p=i;if(Math.abs(M[p][c])<1e-15)return null;[M[c],M[p]]=[M[p],M[c]];const d=M[c][c];for(let j=0;j<2*n;j++)M[c][j]/=d;for(let i=0;i<n;i++)if(i!==c){const f=M[i][c];for(let j=0;j<2*n;j++)M[i][j]-=f*M[c][j]}}return M.map(r=>r.slice(n))}
function dot(a,b){return a.reduce((s,x,i)=>s+x*b[i],0)}
function read(){return{preset:$('preset').value,kTR:num('kTR'),kTF:num('kTF'),kTH:num('kTH'),kRF:num('kRF'),kRH:num('kRH'),kFH:num('kFH'),mT:num('mT'),mR:num('mR'),mF:num('mF'),mH:num('mH'),mTR:num('mTR'),mTF:num('mTF'),mTH:num('mTH'),mRF:num('mRF'),mRH:num('mRH'),mFH:num('mFH'),gR:num('gR'),gF:num('gF'),gH:num('gH'),c4:num('c4'),safety:num('safety')}}
function matrices(p){const K=[[1,p.kTR,p.kTF,p.kTH],[p.kTR,1,p.kRF,p.kRH],[p.kTF,p.kRF,1,p.kFH],[p.kTH,p.kRH,p.kFH,1]],M=[[p.mT*p.mT,p.mTR,p.mTF,p.mTH],[p.mTR,p.mR*p.mR,p.mRF,p.mRH],[p.mTF,p.mRF,p.mF*p.mF,p.mFH],[p.mTH,p.mRH,p.mFH,p.mH*p.mH]];return{K,M}}
function calc(p){const {K,M}=matrices(p),kev=jacobi(K.map(r=>r.slice())),kmin=Math.min(...kev.values),kmax=Math.max(...kev.values),kratio=kmin/kmax,L=cholesky(K);if(!L)return{bad:true,K,M,kmin,kmax,kratio};const iL=invLower(L),C=mul(mul(iL,M),transpose(iL)),ev=jacobi(C.map(r=>r.slice())),ord=ev.values.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),vals=ord.map(x=>x[0]),vecs=ord.map(([v,i])=>ev.vectors.map(r=>r[i]));const light=vecs[0],thetaFrac=light[0]*light[0]/dot(light,light),heavy=C.slice(1).map(r=>r.slice(1)),invH=inverse(heavy),g=[p.gR,p.gF,p.gH],exchange=invH?dot(g,mul(invH,g.map(x=>[x])).map(r=>r[0])):Infinity,total=p.c4+exchange,ratio=Math.abs(total)/LIMIT,tach=vals.some(v=>v< -1e-12),gap=Math.sqrt(Math.max(0,vals[1]||0)),mix=Math.sqrt(Math.max(0,1-thetaFrac));return{bad:false,K,M,kmin,kmax,kratio,cond:kmax/kmin,C,vals,vecs,thetaFrac,mix,exchange,total,ratio,tach,gap,invH}}
function preset(v){const P={decoupled:{kTR:0,kTF:0,kTH:0,kRF:0,kRH:0,kFH:0,mT:0,mR:3,mF:4,mH:5,mTR:0,mTF:0,mTH:0,mRF:0,mRH:0,mFH:0,gR:0,gF:0,gH:0,c4:0},mild:{kTR:.05,kTF:.03,kTH:.02,kRF:.02,kRH:.01,kFH:.015,mT:0,mR:3,mF:4,mH:5,mTR:.08,mTF:.05,mTH:.04,mRF:.1,mRH:.08,mFH:.06,gR:.1,gF:.08,gH:.06,c4:0},generic:{kTR:.12,kTF:.08,kTH:.06,kRF:.05,kRH:.04,kFH:.03,mT:0,mR:3,mF:4,mH:5,mTR:.2,mTF:.15,mTH:.1,mRF:.2,mRH:.15,mFH:.12,gR:1,gF:1,gH:1,c4:.0795774715459},protected:{kTR:.02,kTF:.01,kTH:.01,kRF:0,kRH:0,kFH:0,mT:0,mR:3,mF:4,mH:5,mTR:0,mTF:0,mTH:0,mRF:0,mRH:0,mFH:0,gR:0,gF:0,gH:0,c4:0}}[v];if(!P)return;Object.entries(P).forEach(([k,val])=>$(k).value=val)}
function render(){const p=read(),r=calc(p);if(r.bad){$('message').textContent='Kinetische Matrix nicht positiv definit.';return}$('kmin').textContent=fmt(r.kmin);$('kcond').textContent=fmt(r.cond);$('m0').textContent=fmt(r.vals[0]);$('gap').textContent=fmt(r.gap);$('thetaFrac').textContent=fmt(r.thetaFrac);$('mix').textContent=fmt(r.mix);$('exchange').textContent=fmt(r.exchange);$('total').textContent=fmt(r.total);$('ratio').textContent=fmt(r.ratio);$('kinAudit').textContent=r.kmin>1e-8?'PASS':r.kmin>0?'MARGINAL':'GHOST';$('tachAudit').textContent=r.tach?'FAIL':'PASS';$('mixAudit').textContent=r.thetaFrac>.99?'THETA-DOMINIERT':r.thetaFrac>.8?'GEMISCHT':'GEOMETRISCH';$('gateAudit').textContent=r.ratio<=1?'PASS':'FAIL';const w=$('window');if(r.ratio<=1&&!r.tach&&r.kmin>1e-8){w.className='window pass';w.querySelector('span').textContent='Reduzierter Mischsektor erfüllt den 0.8-Grenzwert.'}else if(!r.tach&&r.kmin>0&&r.ratio<1e6){w.className='window warnbox';w.querySelector('span').textContent='Mischsektor ist formal stabil, verfehlt den benötigten Wilson-Koeffizienten jedoch.'}else{w.className='window fail';w.querySelector('span').textContent='Kein freigegebener Mischsektor: Ghost/Tachyon oder induzierter Operator zu groß.'}$('rows').innerHTML=r.vals.map((v,i)=>'<tr><td>'+i+'</td><td>'+fmt(v)+'</td><td>'+fmt(Math.sqrt(Math.max(0,v)))+'</td><td>'+fmt(r.vecs[i][0]*r.vecs[i][0]/dot(r.vecs[i],r.vecs[i]))+'</td><td>'+names.map((n,j)=>n+': '+fmt(r.vecs[i][j])).join('<br>')+'</td></tr>').join('');$('more').innerHTML='λmin(K)='+fmt(r.kmin)+'<br>λmax(K)='+fmt(r.kmax)+'<br>λmin/λmax='+fmt(r.kratio)+'<br>c_exchange='+fmt(r.exchange)+'<br>c_direct='+fmt(p.c4)+'<br>|c_total|/Grenze='+fmt(r.ratio)+'<br>Robustheitsfaktor s='+fmt(p.safety);let msg='';if(r.kmin<=0)msg+='Kinetischer Ghost. ';if(r.tach)msg+='Mindestens eine tachyonische Eigenrichtung. ';if(r.mix>.1)msg+='Die leichte Mode besitzt relevante geometrische Beimischung. ';if(Math.abs(r.exchange)>LIMIT)msg+='Der schwere geometrische Austausch allein überschreitet die 0.8-Grenze. ';if(Math.abs(p.c4)>LIMIT)msg+='Der direkte Quartikrest überschreitet die Grenze. ';if(r.ratio<=1)msg+='Der reduzierte Benchmark passiert nur unter den aktuell eingegebenen Schutzannahmen. ';$('message').textContent=msg+'Das Resultat ist kein vollständiges 6D-Matching, da die Matrixelemente noch nicht aus COS-02.2B abgeleitet sind.';draw(r)}
function draw(r){const c=$('chart'),b=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(320,b.width),h=Math.max(300,b.height);c.width=w*d;c.height=h*d;const g=c.getContext('2d');g.setTransform(d,0,0,d,0,0);g.clearRect(0,0,w,h);const pad={l:54,r:20,t:20,b:42},W=w-pad.l-pad.r,H=h-pad.t-pad.b,max=Math.max(1,...r.vals.map(v=>Math.abs(v))),X=i=>pad.l+W*(i+.5)/4,Y=v=>pad.t+H*(1-v/max);g.strokeStyle='#294052';g.fillStyle='#a9bdcb';g.font='10px system-ui';g.beginPath();g.moveTo(pad.l,Y(0));g.lineTo(pad.l+W,Y(0));g.stroke();r.vals.forEach((v,i)=>{const x=X(i),y=Y(Math.max(0,v)),base=Y(0);g.fillStyle=v<0?'#ff829f':'#74cfff';g.fillRect(x-24,Math.min(y,base),48,Math.abs(base-y));g.fillStyle='#dbe8ef';g.fillText('m²'+i,x-10,h-12);g.fillText(fmt(v),x-24,Math.max(12,y-5))});g.save();g.translate(13,h/2+25);g.rotate(-PI/2);g.fillText('kanonische Eigenwerte m²',0,0);g.restore()}
$('preset').onchange=()=>{preset($('preset').value);render()};$('run').onclick=render;$('zeroGeo').onclick=()=>{['gR','gF','gH','mTR','mTF','mTH'].forEach(id=>$(id).value=0);render()};$('setLimit').onclick=()=>{$('c4').value=LIMIT;render()};$('profile').onclick=()=>location.href='./baryogenesis-mixed-sector.json';document.querySelectorAll('input,select').forEach(x=>x.addEventListener('change',()=>{if(x.id!=='preset')render()}));addEventListener('resize',render,{passive:true});render();
})();