const { chromium } = require('playwright');
const assert = require('assert');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:412,height:915}});
  const errors=[];
  page.on('pageerror',e=>errors.push(String(e)));
  await page.goto('http://127.0.0.1:4173/UniverseLab/2026-08-29_UniverseLab_Hyperzeit_10M_ResearchProgram_v1.0.html',{waitUntil:'networkidle'});
  const wrap=page.locator('[data-ul-language-switcher]');
  const select=wrap.locator('select');
  const gates=page.locator('.ul-shell__gates');
  await select.waitFor({state:'visible',timeout:10000});
  assert.strictEqual(await select.locator('option').count(),11,'expected 11 languages');
  const box=await wrap.boundingBox();
  const gatesBox=await gates.boundingBox();
  assert(box && box.x>=0 && box.x+box.width<=412.5,'language selector must stay inside mobile viewport');
  assert(gatesBox && box.y>=gatesBox.y-1 && box.y+box.height<=gatesBox.y+gatesBox.height+1,'language selector must remain inside shell gate row');
  const parentClass=await wrap.evaluate(el=>el.parentElement?.className||'');
  assert(String(parentClass).includes('ul-shell__gates'),'language selector must be a child of shell gates');
  const pos=await wrap.evaluate(el=>getComputedStyle(el).position);
  assert.strictEqual(pos,'static','language selector must not be floating/fixed');
  assert.strictEqual(await select.inputValue(),'de');
  assert.deepStrictEqual(errors,[],'page must have no JS errors');

  await page.goto('http://127.0.0.1:4173/UniverseLab/navigator.html',{waitUntil:'networkidle'});
  const navWrap=page.locator('[data-ul-language-switcher]');
  const navSelect=navWrap.locator('select');
  const navGates=page.locator('.ul-shell__gates');
  await navSelect.waitFor({state:'visible',timeout:10000});
  const navBox=await navWrap.boundingBox();
  const navGatesBox=await navGates.boundingBox();
  assert(navBox && navGatesBox && navBox.y>=navGatesBox.y-1 && navBox.y+navBox.height<=navGatesBox.y+navGatesBox.height+1,'navigator language selector must stay in top shell gate row');
  await Promise.all([page.waitForURL(/navigator-en\.html/,{timeout:10000}),navSelect.selectOption('en')]);
  assert(/navigator-en\.html$/.test(new URL(page.url()).pathname),'English must use curated navigator route');
  await browser.close();
  console.log('Language switcher shell placement contract: PASS');
})().catch(e=>{console.error(e);process.exit(1)});
