import {seededRandom} from './numerics.js';
import {CellularAutomaton} from './cellular.js';
import {CosmologyController} from './cosmology-controller.js';
import {drawSimulation,drawChart} from './chart.js';
import {saveState,loadState,exportCsv} from './storage.js';
const $=s=>document.querySelector(s),sim=$('#sim'),chart=$('#chart'),ca=new CellularAutomaton(),cosmo=new CosmologyController();let history=[],running=false,last=0,acc=0,rng=seededRandom(20260717);
function params(){const Or=+$('#or').value,Om=+$('#om').value,Ol=+$('#ol').value;return{H0:+$('#h0').value,Or,Om,Ol,Ok:1-Or-Om-Ol}}
function resetRng(){rng=seededRandom((+$('#randomSeed').value||0)>>>0)}
function seed(){resetRng();ca.seed($('#preset').value,+$('#density').value,rng);cosmo.reset();history=[];record();draw()}
function record(){const p=params(),s=cosmo.snapshot(p),live=ca.liveCount(),regime=s.q< -1e-6?'beschleunigt':s.q>1e-6?'verzögert':'Übergang';history.push({generation:ca.generation,N:ca.N,live,density:live/(ca.N*ca.N),a:s.a,E:s.E,tau:s.tau,Or:s.fractions.r,Om:s.fractions.m,Ok:s.fractions.k,Ol:s.fractions.l,q:s.q,dominant:s.dominant.transition||s.dominant.dominant,regime,closure:s.fractions.closure,accepted:s.accepted,rejected:s.rejected});if(history.length>2500)history.shift()}
function step(){ca.step($('#rule').value,+$('#noise').value,rng);const mode=$('#expMode').value;if(mode==='heuristic'){const e=+$('#expand').value;if(e&&ca.generation%Math.max(8,Math.round(110-e))===0)ca.setSize(ca.N+2)}else if(mode==='lcdm'){const dt=2e-5*+$('#timeScale').value;if(!cosmo.advance(dt,params())){running=false;$('#play').textContent='▶ Start'}}const target=Math.round(120+28*Math.log10(Math.max(1,cosmo.a/1e-3)));if(mode==='lcdm'&&target>ca.N)ca.setSize(Math.min(260,target));record();draw()}
function draw(){drawSimulation(sim,ca);drawChart(chart,history);const p=params(),s=cosmo.snapshot(p),live=ca.liveCount(),label={radiation:'Strahlung',matter:'Materie',curvature:'Krümmung',lambda:'Vakuum',invalid:'ungültig'};$('#hud').innerHTML=`Generation: ${ca.generation}<br>Gitter: ${ca.N} × ${ca.N}<br>Aktiv: ${live.toLocaleString('de-DE')}<br>Dichte: ${(100*live/ca.cells.length).toFixed(2)} %<br>a: ${s.a.toExponential(3)}<br>E(a): ${Number.isFinite(s.E)?s.E.toExponential(3):'–'}<br>Ωₖ₀: ${p.Ok.toFixed(4)}`;$('#epoch').textContent=s.dominant.transition?`Übergang ${s.dominant.transition}`:(label[s.dominant.dominant]||s.dominant.dominant);$('#regime').textContent=s.q< -1e-6?'beschleunigt':s.q>1e-6?'verzögert':'Übergang';$('#qMetric').textContent=Number.isFinite(s.q)?s.q.toFixed(6):'–';$('#rkMetric').textContent=`${s.accepted}/${s.rejected}`;$('#error').textContent=s.error?`Integration gestoppt: ${s.error}`:'';$('#seedOut').value=String((+$('#randomSeed').value||0)>>>0)}
function bind(id,out,fmt){const el=$(id),o=$(out),f=()=>{o.value=fmt(el.value);draw()};el.oninput=f;f()}
bind('#speed','#speedOut',v=>v+' Hz');bind('#density','#densityOut',v=>v+' %');bind('#noise','#noiseOut',v=>v==='0'?'aus':v);bind('#expand','#expandOut',v=>v+' %');bind('#h0','#h0Out',v=>(+v).toFixed(1));bind('#om','#omOut',v=>(+v).toFixed(3));bind('#or','#orOut',v=>(+v).toExponential(2));bind('#ol','#olOut',v=>(+v).toFixed(3));bind('#timeScale','#timeOut',v=>v+'×');$('#randomSeed').oninput=draw;
$('#expMode').onchange=()=>{$('#lcdmBox').classList.toggle('on',$('#expMode').value==='lcdm');$('#heurBox').classList.toggle('on',$('#expMode').value==='heuristic');draw()};$('#play').onclick=()=>{running=!running;$('#play').textContent=running?'⏸ Pause':'▶ Start'};$('#step').onclick=step;$('#seedBtn').onclick=seed;$('#clear').onclick=()=>{ca.clear();history=[];record();draw()};$('#preset').onchange=seed;
sim.addEventListener('pointerdown',paint);sim.addEventListener('pointermove',e=>{if(e.buttons)paint(e)});function paint(e){const r=sim.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*ca.N),y=Math.floor((e.clientY-r.top)/r.height*ca.N);ca.paint(x,y);draw()}
$('#save').onclick=()=>saveState({cellular:ca.serialize(),cosmology:cosmo.serialize(),history,settings:Object.fromEntries([...document.querySelectorAll('input,select')].map(e=>[e.id,e.value]))});$('#load').onclick=()=>{try{const d=loadState();if(!d)return;Object.entries(d.settings||{}).forEach(([k,v])=>{const e=$('#'+k);if(e)e.value=v});if(d.cellular)ca.restore(d.cellular);else ca.restore({N:d.N,generation:d.generation,cells:d.cells||d.a});if(d.cosmology)cosmo.restore(d.cosmology);else cosmo.restore({a:d.scaleFactor,tau:d.tau});history=d.history||[];resetRng();$('#expMode').dispatchEvent(new Event('change'));draw()}catch(e){$('#error').textContent='Speicherstand konnte nicht geladen werden.'}};$('#export').onclick=()=>exportCsv(history);
let deferred;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#install').hidden=true}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
function loop(t){const dt=Math.min(.1,(t-last)/1000||0);last=t;if(running){acc+=dt;const d=1/+$('#speed').value;while(acc>d){step();acc-=d}}requestAnimationFrame(loop)}
seed();requestAnimationFrame(loop);
